### ISSUE TITLE
how run this in apache2 

### ISSUE THREAD

**Issue by ghost** [rif/lov3lyme#1]
thank's for you'r job

**Comment by rif** [comment]
As far as I can remember you just have to build it and run the cmo binary. There is no need for a generic web server but you can use one as proxy for the server created in the code.

There is an un-maintained running version of this code here: http://lov3lyme-rif.rhcloud.com/.

This is an abandoned project made open source to answer a reddit request for a sample web app made without a webframework.

**Comment by ghost** [comment]
thank you sp much
